MERGE INTO tier
    VALUES (1, 'FREE', 0.0);
MERGE INTO tier
    VALUES (2, 'BRONZE', 5.0);
MERGE INTO tier
    VALUES (3, 'SILVER', 10.0);
MERGE INTO tier
    VALUES (4, 'GOLD', 20.0);
MERGE INTO tier
    VALUES (5, 'PLATINUM', 30.0);

